// react-todo/src/App.js
import { useEffect, useState } from 'react';

function App() {

  return (
      <TodoList />
  );

}

function TodoList() {
  const [todos, setTodos] = useState([]);
  const [title, setTitle] = useState("");

  useEffect(() => {
    // set initial to do items
    setTodos([
      {title: "My task", done: false},
      {title: "My task 2", done: true},
      {title: "My task 3", done: true},
    ])
  }, []);

  function removeTodoItem(index) {
    setTodos(todos => todos.filter((_, i) => i !== index));
  }

  function toggleDone(index){
    setTodos(todos => todos.map((todo, i) => {
        if(i === index) {
          return {...todo, done: !todo.done}
        }
        else {
          return todo;
        }
      })
    );
  }

  function titleChanged(e) {
    setTitle(e.target.value);
  }

  function addTodoItem() {
    if(title === "") {
      alert("Title cannot be empty");
      return;
    }

    setTodos(todos => [...todos, {
      title: title,
      done: false,
    }]);

    setTitle("");
  }

  return (
    <div>
        {todos.map((todo, index) => 
          <TodoItem 
            key={index}
            index={index} 
            title={todo.title} 
            done={todo.done} 
            onRemoveClicked={removeTodoItem} 
            onCheckboxClicked={toggleDone} />)}
        <input type="text" value={title} onChange={titleChanged} />
        <button onClick={addTodoItem}>Add</button>
    </div>
  )
}

function TodoItem({title, done, index, onRemoveClicked, onCheckboxClicked}) {
  return (
      <div>
        <input type="checkbox" defaultChecked={done} onClick={() => onCheckboxClicked(index)}/> :
        <span style={{textDecoration: (done ? "line-through" : "none")}}>{title}</span>
        <button onClick={() => onRemoveClicked(index)}>remove</button>
      </div>
  )
}

export default App;

// solid-todo/src/App.jsx
import { createSignal, For } from "solid-js";

function App() {
  return (
    <TodoList />
  );
}

function TodoList() {

  const [todos, setTodos] = createSignal([
    { title: "my task 1", done: true },
    { title: "another task", done: false },
    { title: "other task", done: false },
  ]);

  const [newTodo, setNewTodo] = createSignal("");

  function toggleDone(index) {
    setTodos(todos().map((todo, idx) => {
      if (idx == index) {
        return { ...todo, done: !todo.done };
      } 

      return todo;
    }));
  }

  function handleChange(e) {
    setNewTodo(e.target.value);
  }

  function addTodo() {
    setTodos([
      ...todos(),
      { title: newTodo(), done: false},
    ]);

    setNewTodo("");
  }

  function removeTodo(toBeRemoved) {
    console.log(toBeRemoved);
    setTodos(todos().filter((_, idx) => (idx !== toBeRemoved)));
  }

  return (
    <>
    <For each={todos()}>
      {(todo, index) => <TodoItem index={index} todo={todo} toggleDone={toggleDone} removeTodo={removeTodo} />}
    </For>
    <div>
      <input type="text" value={newTodo()} onChange={e => handleChange(e)} />
        <button onClick={() => addTodo()}>Add</button>
    </div>
    </>
  );
}

function TodoItem({index, todo, toggleDone, removeTodo}) {
  return (
    <div>
      <input type="checkbox" checked={todo.done} onClick={() => toggleDone(index())} />
      <span style={styles.titleStyle(todo.done)}>{todo.title}</span>
      <button onClick={() => removeTodo(index())}>remove</button>
    </div>
  )
}


const styles = {
  titleStyle: (done) => ({ "text-decoration": (done ? "line-through" : "none") })
};

export default App;
